linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/maxgio92/monkaos) # Groups all imports with the specified Prefix.

linters:
  enable-all: true
  disable:
    - interfacer
    - godox
    - golint
    - scopelint
    - maligned
    - gochecknoglobals
    - gochecknoinits
    - exhaustivestruct
    - exhaustruct
    - ireturn
    - lll
    - wrapcheck
    - varnamelen
    - whitespace
    - wsl
    - gofumpt
    - godot
    - deadcode
    - gci
    - goerr113
    - gomnd
    - cyclop
    - testpackage

run:
  skip-dirs:
    - pkg/matrix
    - pkg/template
