name: CI

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:

  build:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check out code
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0

    - name: Lint code
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: v1.46.2
        only-new-issues: false
        args: --config .golangci.yml

    - name: Build
      run: make test
